application: your_appid
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fetch\.py
  script: wsgi.app
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
